#! /usr/bin/env bash

set -e

TOOLCHAIN_CMAKE_OUT=cmake-toolchain.cmake

cat << EOF > ${TOOLCHAIN_CMAKE_OUT}
set(CMAKE_CROSSCOMPILING ON)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_SYSTEM_VERSION 1)

set(GCC_COMPILER_VERSION "${V_GCC}" CACHE STRING "GCC Compiler version")

set(CMAKE_C_COMPILER \${CMAKE_CURRENT_LIST_DIR}/bin/${TARGET_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER \${CMAKE_CURRENT_LIST_DIR}/bin/${TARGET_PREFIX}-g++)
set(CMAKE_AR \${CMAKE_CURRENT_LIST_DIR}/bin/${TARGET_PREFIX}-ar)
set(CMAKE_LINKER \${CMAKE_CURRENT_LIST_DIR}/bin/${TARGET_PREFIX}-ld)
set(CMAKE_FIND_ROOT_PATH "\${CMAKE_CURRENT_LIST_DIR}/${TARGET_PREFIX}/")

# Use host tools
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# Only ever build/link to sysroot
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

EOF

cat $TOOLCHAIN_CMAKE_OUT
