#! /usr/bin/env bash

source "$ROOT_DIR/scripts/repack_tools.sh" || exit

rm -rf tree-{build,install}
mkdir tree-{build,install}
if [ "$WPITARGET" != "sysroot" ]; then
    for dir in {sysroot,libcxx,conf}-install; do
        echo "$dir/"
        rsync "$dir/" tree-build -a --copy-links
    done
    echo "${ROOT_DIR}/build/${WPITARGET}/llvm-install/"
    rsync "${ROOT_DIR}/build/${WPITARGET}/llvm-install/" tree-build -a --copy-links
else
    pushd "sysroot-install"
    # fix-links
    popd
    rsync "sysroot-install/" tree-build -a --copy-links
fi
mv "cmake-toolchain.cmake" "tree-build/${WPIPREFIX}"
pushd tree-build
du -hs .

WPI_TREE_OUT="frc${V_YEAR}/${TOOLCHAIN_NAME}/"

rm -rf "${WPI_TREE_OUT}"
mkdir -p "${WPI_TREE_OUT}"

rsync -a "./${TARGET_TUPLE}/" "${WPI_TREE_OUT}/${TARGET_TUPLE}"
rsync -a "./${WPIPREFIX}/" "${WPI_TREE_OUT}/"
rm -rf "./${WPIPREFIX}/"

pushd "${WPI_TREE_OUT}"
pushd bin
cp clang "${TARGET_TUPLE}-clang"
cp clang++ "${TARGET_TUPLE}-clang++"
popd
rm -rf share/info share/man
rm -rf lib/xtables
du -hs .

popd # frcYYYY/
popd # tree-build

mv "tree-build/frc${V_YEAR}/" "tree-install/frc${V_YEAR}"
