name: Build Lite - Linux Only

on:
  pull_request:
  push:
    branches-ignore:
      - "stable"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            { os: roborio, port: armel },
            { os: bionic, port: armhf },
            { os: bionic, port: arm64 },
            { os: focal, port: armhf },
            { os: focal, port: arm64 },
            { os: buster, port: armhf },
            { os: buster, port: arm64 },
            { os: bullseye, port: armhf },
            { os: bullseye, port: arm64 },
          ]
    name: Build ${{ matrix.target.os }}-${{ matrix.target.port }} for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build on docker
        run: ./build-docker.sh 16.04 hosts/linux_x86_64.env targets/${{matrix.target.os}} ${{matrix.target.port}}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.target.os}}-${{matrix.target.port}}-linux_x86_64
          path: build/${{matrix.target.os}}-${{matrix.target.port}}/*/${{matrix.target.port}}-${{matrix.target.os}}-*-*-Toolchain-*.*
  test-sysroot:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target:
          [
            { os: roborio, port: armel },
            { os: bionic, port: armhf },
            { os: bionic, port: arm64 },
            { os: focal, port: armhf },
            { os: focal, port: arm64 },
            { os: buster, port: armhf },
            { os: buster, port: arm64 },
            { os: bullseye, port: armhf },
            { os: bullseye, port: arm64 },
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{matrix.target.os}}-${{matrix.target.port}}-linux_x86_64
      - name: Fix directory
        run: mv Linux/* .
      - name: Print directory for logging
        run: ls -lah
      - name: Run test
        run: ./test.sh hosts/linux_x86_64.env targets/${{matrix.target.os}} ${{matrix.target.port}}
